# Generated by Django 5.2.1 on 2025-05-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="description",
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending Approval", "Pending Approval"),
                    ("Approved", "Approved"),
                ],
                default="Approval",
                max_length=50,
            ),
        ),
    ]
