# Generated by Django 5.2.1 on 2025-05-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_remove_project_description_alter_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="fund",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
