# Generated by Django 5.2.1 on 2025-05-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_fund"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending Approval", "Pending Approval"),
                    ("Approved", "Approved"),
                ],
                default="Approved",
                max_length=50,
            ),
        ),
    ]
