# Generated by Django 5.2.1 on 2025-05-15 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_project_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="total_contribution_expenditure_diff",
        ),
    ]
