# Generated by Django 5.2.1 on 2025-05-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_remove_project_total_contribution_expenditure_diff"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="total_contribution_expenditure_diff",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
