from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ProjectViewSet, ProjectsByCountryView, ProjectsByStatusView


router = DefaultRouter()
router.register(r'projects', ProjectViewSet, basename='project')


urlpatterns = [
    # Include the URLs generated by the router (for ProjectViewSet)
    path('', include(router.urls)),

    # Custom URL for filtering projects by country name
    # <str:country_name> captures the country name from the URL as a string
    path('projects/country/<str:country_name>/', ProjectsByCountryView.as_view(), name='projects-by-country'),

    # Custom URL for filtering projects by status key
    # <str:status_key> captures the status key from the URL as a string
    path('projects/status/<str:status_key>/', ProjectsByStatusView.as_view(), name='projects-by-status'),

    # Optional: URLs for listing other models if you uncommented those views
    # path('countries/', CountryListView.as_view(), name='country-list'),
    # path('themes/', ThemeListView.as_view(), name='theme-list'),
    # ... add paths for LeadOrgUnit and Donor lists if needed

]