# projects/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    ProjectViewSet,
    ProjectsByCountryView,
    ProjectsByStatusView,
    ProjectCountByCountryView,
    ProjectCountByLeadOrgUnitView,
    ProjectCountByThemeView,
    WorldMapProjectDataView,
    AIInsightView,
    # Import the new ViewSets for related models
    CountryViewSet,
    LeadOrgUnitViewSet,
    ThemeViewSet,
    DonorViewSet,
)

# Create a router and register viewsets
router = DefaultRouter()
# Register the ProjectViewSet
router.register(r'projects', ProjectViewSet, basename='project')
# Register the new ViewSets for related models
router.register(r'countries', CountryViewSet)
router.register(r'lead-org-units', LeadOrgUnitViewSet)
router.register(r'themes', ThemeViewSet)
router.register(r'donors', DonorViewSet)


# Define URL patterns
urlpatterns = [
    # --- Specific Custom URLs (Must come before the general router include) ---

    # Custom URL for filtering projects by country name
    path('projects/country/<str:country_name>/', ProjectsByCountryView.as_view(), name='projects-by-country'),

    # Custom URL for filtering projects by status key
    path('projects/status/<str:status_key>/', ProjectsByStatusView.as_view(), name='projects-by-status'),

    # --- URLs for Dashboard Aggregated Data ---
    path('projects/summary/by_country/', ProjectCountByCountryView.as_view(), name='project-count-by-country'),
    path('projects/summary/by_org_unit/', ProjectCountByLeadOrgUnitView.as_view(), name='project-count-by-org-unit'),
    path('projects/summary/by_theme/', ProjectCountByThemeView.as_view(), name='project-count-by-theme'),
    path('projects/summary/world_map_data/', WorldMapProjectDataView.as_view(), name='world-map-project-data'),

    # --- URL for AI Insights ---
    path('projects/insights/', AIInsightView.as_view(), name='ai-insights'),

    # --- General Router Include (Must come AFTER more specific paths) ---
    # Include the URLs generated by the router (for all registered ViewSets)
    # This will now handle /countries/, /lead-org-units/, /themes/, /donors/
    # as well as /projects/, /projects/{id}/ etc.
    # Place this last so that specific paths like /projects/insights/ are checked first.
    path('', include(router.urls)),
]

# Optional: Define an app_name for namespacing URLs
# app_name = 'projects'
